Repository MAK-E-AT/Backend, pull requests merged in 2023-04, with the labels that each got.

#12 [feat] 백엔드 초기 세팅
  makeat_be/.gitignore
  makeat_be/build.gradle
  makeat_be/gradle/wrapper/gradle-wrapper.jar
  makeat_be/gradle/wrapper/gradle-wrapper.properties
  makeat_be/gradlew
  makeat_be/gradlew.bat
  makeat_be/settings.gradle
  makeat_be/src/main/java/io/makeat/makeat_be/MakeatBeApplication.java
  makeat_be/src/main/resources/application.properties
  makeat_be/src/test/java/io/makeat/makeat_be/MakeatBeApplicationTests.java
Labels: Status: In Review 👀, BE 🦁, Type: Task

#25 [feat] 네이버 로그인 기능
  makeat_be/src/main/java/io/makeat/makeat_be/controller/NaverLoginController.java
  makeat_be/src/main/java/io/makeat/makeat_be/service/NaverLoginService.java
  makeat_be/src/main/resources/application.yml
Labels: Status: Done 🪄, Type: Feature, BE 🦁

#48 <develop> -> <feature/refactor-for-mvc>
  makeat_be/build.gradle
  makeat_be/keystore.p12
  makeat_be/src/main/java/io/makeat/makeat_be/config/AuthenticationConfig.java
  makeat_be/src/main/java/io/makeat/makeat_be/config/JwtFilter.java
  makeat_be/src/main/java/io/makeat/makeat_be/controller/UserController.java
  makeat_be/src/main/java/io/makeat/makeat_be/service/KakaoLoginService.java
  makeat_be/src/main/java/io/makeat/makeat_be/service/LoginService.java
  makeat_be/src/main/java/io/makeat/makeat_be/service/NaverLoginService.java
  makeat_be/src/main/java/io/makeat/makeat_be/service/UserService.java
  makeat_be/src/main/java/io/makeat/makeat_be/utils/JwtUtil.java
  makeat_be/src/main/resources/application.yml
Labels: Status: In Progress 💻, Type: Feature, BE 🦁
